import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
const root=new URL("..",import.meta.url).pathname,out=join(root,"dist");
const css=["styles.css","media.css","hero.css"].map(f=>readFileSync(join(root,"src",f),"utf8")).join("");
const host="https://brinesalters.com",phone="604-761-1518",email="wow@plowwow.com";
const nav=`<header class="top"><nav class="wrap nav"><a class="brand" href="/"><span>BRINE</span>SALTERS.COM</a><div class="navlinks"><a href="/services/">Services</a><a href="/equipment/">Equipment</a><a href="/service-areas/">Service Areas</a><a href="/guides/">Guides</a><a href="/faq/">FAQ</a><a href="/about/">About</a></div><a class="button" href="/contact/">Get a quote</a></nav></header>`;
const footer=`<footer><div class="wrap"><div class="foot"><div><strong>BrineSalters.com</strong><p>Practical commercial anti-icing, salting and de-icing guidance. Eligible service enquiries are handled by PlowWow.</p></div><div><strong>Authority</strong><a href="/faq/">FAQ</a><a href="/editorial-policy/">Editorial policy</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a></div><div><strong>Contact</strong><a href="tel:+16047611518">${phone}</a><a href="mailto:${email}">${email}</a><a href="https://plowwow.com/">PlowWow.com</a></div></div></div></footer><a class="mobile-call" href="tel:+16047611518">Call for winter service · ${phone}</a>`;
const contactCard=`<aside class="contact-floater" aria-label="Contact PlowWow"><button class="floater-close" type="button" aria-label="Hide contact card" onclick="this.parentElement.remove()">×</button><div class="floater-head"><img src="/assets/plowwow/wow-mascot-card.png" alt=""><div><span>PlowWow service desk</span><strong>Fast quotes & storm help</strong></div></div><div class="floater-actions"><a href="tel:+16047611518"><span><small>Call now</small>${phone}</span><b>☎</b></a><a href="sms:+16047611518"><span><small>Text</small>${phone}</span><b>↗</b></a><a href="mailto:${email}"><span><small>Email</small>${email}</span><b>✉</b></a></div></aside>`;
const org={"@context":"https://schema.org","@type":"Organization","@id":`${host}/#organization`,name:"BrineSalters.com",url:`${host}/`,telephone:"+1-604-761-1518",email};
const esc=s=>s.replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;");
const bread=(path,title)=>({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`${host}/`},{"@type":"ListItem",position:2,name:title,item:`${host}${path}`}]});
function page(path,title,description,body,schemas=[]){const canonical=`${host}${path}`;const html=`<!doctype html><html lang="en-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${host}/assets/generated/commercial-brine-truck-v2.png"><meta name="twitter:card" content="summary_large_image"><style>${css}</style>${[org,bread(path,title),...schemas].map(s=>`<script type="application/ld+json">${JSON.stringify(s)}</script>`).join("")}</head><body>${nav}${body}${footer}${contactCard}</body></html>`;const file=join(out,path,"index.html");mkdirSync(dirname(file),{recursive:true});writeFileSync(file,html)}
const faq=[
["What is liquid brine?","A water-and-salt solution used in suitable conditions for preventive anti-icing or as part of a de-icing program."],
["What is the difference between anti-icing and de-icing?","Anti-icing is preventive treatment before suitable events. De-icing addresses frozen material or a bond that already exists."],
["Does brine replace snow plowing?","No. Accumulating snow still requires mechanical clearing. Brine can help reduce bonding at the pavement surface."],
["When should a property be pre-treated?","Timing depends on pavement temperature, forecast precipitation, product choice and the expected start of the event."],
["Why does pavement temperature matter?","De-icer performance occurs at the pavement, which can be warmer or colder than the surrounding air."],
["Can brine be applied during rain?","Rain can dilute or wash material away. The expected transition and timing must be reviewed."],
["Is brine safe for concrete?","Compatibility depends on the product and the surface's age, condition and requirements."],
["Is brine safe around landscaping?","No de-icer is impact-free. Measured application, drainage awareness and avoiding overspray reduce unnecessary exposure."],
["How much brine should be applied?","There is no universal rate. Product documentation, conditions, objectives and calibrated equipment determine the plan."],
["Why calibrate a sprayer?","Calibration connects output, travel speed and treatment width to a repeatable application rate."],
["What equipment applies liquid brine?","Common systems include truck-mounted tanks and spray bars, skid units, hose reels and walk-behind sprayers."],
["How is a sprayer sized?","Measure route area, target rate, refill interval, available payload and application width."],
["Can a brine tank overload a pickup?","Yes. Vehicle payload, axle loading, securement and tank baffling must be reviewed."],
["What should commercial sites prioritize?","Emergency access, main lanes, loading areas, accessible stalls, entrances and pedestrian routes."],
["Are sidewalks included with lot salting?","Only when listed in the scope. They require different labour, equipment and timing."],
["Why do parkade ramps refreeze?","Shade, wind, drainage, tracked moisture and thermal mass can keep ramps colder than nearby pavement."],
["Do industrial yards need a different plan?","Yes. Trailer movement, gates, shift changes and restricted areas affect treatment sequencing."],
["What belongs in a service record?","Arrival, observed conditions, serviced areas, material used, exceptions and follow-up notes."],
["Does treatment guarantee a slip-free surface?","No. Conditions change continuously; inspection, clearing, treatment and access controls may all be required."],
["Who provides actual service?","Eligible Lower Mainland commercial and strata enquiries are handled through PlowWow's active routes."],
["Is emergency service always available?","No. Availability depends on conditions and route capacity, and seasonal clients may receive priority."],
["Which cities are covered?","Planning pages cover Metro Vancouver and the Fraser Valley; service is confirmed property by property."],
["Can I request material supply?","Use the contact page with required product, volume, storage and timing; availability must be confirmed."],
["Are the equipment images specifications?","No. Generated images illustrate common layouts; actual installations follow manufacturer requirements."]];
const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
page("/faq/","Brine, Salting & De-Icing FAQ | BrineSalters.com","Direct answers about liquid brine, commercial salting, equipment, parkade ramps and Lower Mainland winter service.",`<main><section class="hero"><div class="wrap"><p class="eyebrow">Answer centre</p><h1>Brine, salting and de-icing questions—answered.</h1><p>Clear answers for property teams, strata councils, facility operators and winter contractors.</p></div></section><section class="section"><div class="wrap content">${faq.map(([q,a])=>`<div class="faq"><h2>${q}</h2><p>${a}</p></div>`).join("")}</div></section></main>`,[faqSchema]);
page("/editorial-policy/","Editorial & Technical Content Policy | BrineSalters.com","How BrineSalters.com handles technical guidance, operational claims, generated imagery and corrections.",`<main><section class="hero"><div class="wrap"><p class="eyebrow">Trust and methodology</p><h1>Editorial and technical content policy.</h1></div></section><section class="section"><div class="wrap content"><h2>Scope</h2><p>Content explains common winter-surface planning and equipment. It does not replace labels, engineering advice, vehicle ratings or site procedures.</p><h2>Claims and corrections</h2><p>We avoid unsupported coverage, performance and safety guarantees. Operational availability is confirmed property by property. Corrections can be requested at ${email}.</p><h2>Generated imagery</h2><p>Some images illustrate plausible equipment configurations. They are not manufacturer drawings or installation approval.</p><h2>Commercial relationship</h2><p>Eligible enquiries are directed to PlowWow. Contextual links help readers reach the operator; they are not an artificial backlink network.</p></div></section></main>`);
page("/privacy/","Privacy Policy | BrineSalters.com","Privacy information for BrineSalters.com website visitors and service enquiries.",`<main><section class="hero"><div class="wrap"><h1>Privacy policy.</h1></div></section><section class="section"><div class="wrap content"><p>No account is required. Information supplied by phone or email may be used by PlowWow to respond, assess availability and prepare a proposal. Do not send passwords, payment-card information or unrelated sensitive data.</p><h2>Technical data</h2><p>Hosting and analytics providers may process standard browser, device, referral and approximate-location information according to the services configured at deployment.</p><h2>Contact</h2><p>Questions can be sent to ${email}.</p></div></section></main>`);
page("/terms/","Website Terms | BrineSalters.com","Website-use terms and technical-information limitations for BrineSalters.com.",`<main><section class="hero"><div class="wrap"><h1>Website terms.</h1></div></section><section class="section"><div class="wrap content"><p>Information is general education. Actual application, equipment installation and service require site review and compliance with labels, manufacturer documentation, contracts and applicable requirements.</p><h2>No performance guarantee</h2><p>Conditions change. Content does not guarantee surface condition, application results, response time or availability.</p><h2>Quotes and contracts</h2><p>A call or email is an enquiry, not a service contract. Scope, pricing, triggers and availability require a written proposal.</p></div></section></main>`);
console.log("Built FAQ and trust authority pages.");
